### ISSUE TITLE
Import path is wrong by one level

### ISSUE THREAD

**Issue by ilyavf** [donejs/done-component#17]
Similar to #16, but with different syntax:

With the following file structure:
```
src/
    components/
        grids/
            my-grid.component
            my-grid.stache
```

I cannot use "./" to reference stache template from inside .component:
```
<can-component tag="most-active-grid">
  <template>
      <div>
            {{> templateGrid}}
      </div>
    </drag-panel>
  </template>
  <script type="view-model">
    import Map from 'can/map/';
    import templateGrid from './my-grid.stache';
    export default Map.extend({
      templateGrid: templateGrid
    });
  </script>
</can-component>
```
Steal is trying to load template file from `src/components/grids/my-grid.component/my-grid.stache`.

However "../" works well: `import templateGrid from '../my-grid.stache';`.

**Comment by matthewp** [comment]
Closed by #18
