### ISSUE TITLE
Provide a solution for leakScope

### ISSUE THREAD

**Issue by matthewp** [donejs/done-component#19]
The switch to leakScope: false by default has broken some done-components. We need to provide a way to enable it, probably with a prop:

``` js
<can-component tag="foo-bar" leak-scope>

</can-component>
```

**Comment by matthewp** [comment]
This is fixed in the can3 branch: https://github.com/donejs/done-component/tree/can3

**Comment by phillipskevin** [comment]
The `can3` branch has been moved over to `major`, so this change will land in DoneJS 1.0. Going to close this issue.
