### ISSUE TITLE
Change template to view

### ISSUE THREAD

**Issue by ccummings** [donejs/done-component#20]
In 3.0 `template` is deprecated ([source](https://github.com/canjs/can-component/blob/master/can-component.js#L104)) so the generated code should use `view` instead.

**Comment by phillipskevin** [comment]
@mjstahl are you still planning to land this change?

**Comment by marshallswain** [comment]
The change to the code is done in this PR, but there are some tests that need to be updated: https://github.com/donejs/done-component/pull/21

**Comment by matthewp** [comment]
Fixed by https://github.com/donejs/done-component/pull/21
