### ISSUE TITLE
Rename this project to steal-component

### ISSUE THREAD

**Issue by pYr0x** [donejs/done-component#22]
This project is a steal plugin, so I would prefer to rename it to what it really does.
Maybe rename it to steal-can-component 
@matthewp what do you think.

**Comment by matthewp** [comment]
DoneJS is (mostly) Steal + Can so I think the name is appropriate as done-component. It combines the two.  steal-can-component is the same as done-component 😉

**Comment by matthewp** [comment]
Let's close this unless you feel really strongly about it..
