### ISSUE TITLE
Fix done-component’s broken build

### ISSUE THREAD

**Issue by chasenlehara** [donejs/done-component#64]
At this time, there are [14 open issues](https://github.com/donejs/done-component/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20%22breaking%20the%20build%22) from Greenkeeper about dependency updates breaking the build, and even a [simple typo fix](https://github.com/donejs/done-component/pull/63) isn’t working. There are [multiple alpha devDependencies](https://github.com/donejs/done-component/blob/52eaacd3978ff777e1c8f51860535698c62fdf4d/package.json#L36-L38) being used as well.

**Comment by matthewp** [comment]
Looks to me like the ssr tests are the ones that are failing. It's possible this is caused by a change to done-ssr.

**Comment by matthewp** [comment]
I have a fix.
